import * as assert from 'node:assert';
import * as vscode from 'vscode';
import * as path from 'node:path';
import { readFile, stat } from 'node:fs/promises';

suite('Markdown Reader local diagram runtime', () => {
  test('renders PlantUML and Graphviz with packaged local assets in an opaque Webview', async function () {
    this.timeout(45_000);
    const extension = vscode.extensions.getExtension('chengjian.vscode-markdown-reader')!;
    const framePath = path.join(extension.extensionPath, 'media', 'local-diagram-frame.html');
    await assert.doesNotReject(stat(framePath), 'Local renderer frame must be generated by the extension build');
    const frameHtml = await readFile(framePath, 'utf8');
    const panel = vscode.window.createWebviewPanel('markdownReader.localDiagramTest', 'Local diagram test', vscode.ViewColumn.Active, {
      enableScripts: true,
      localResourceRoots: [extension.extensionUri]
    });
    const resource = (...parts: string[]) => panel.webview.asWebviewUri(vscode.Uri.joinPath(extension.extensionUri, ...parts)).toString();
    const nonce = 'plantuml-runtime-test-nonce';
    const frameUri = `data:text/html;base64,${Buffer.from(frameHtml).toString('base64')}`;
    const finished = new Promise<Record<string, unknown>>((resolve) => {
      panel.webview.onDidReceiveMessage((message) => {
        if (message.type === 'plantumlProbeStage') console.log('Local diagram probe stage:', JSON.stringify(message));
        if (message.type === 'plantumlProbeResult') resolve(message);
      });
    });
    try {
      panel.webview.html = `<!doctype html><html><head>
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; frame-src 'self'; connect-src ${panel.webview.cspSource}; script-src ${panel.webview.cspSource} 'nonce-${nonce}' 'wasm-unsafe-eval'; style-src ${panel.webview.cspSource} 'unsafe-inline';">
<style id="render-styles" nonce="${nonce}"></style></head>
<body data-local-diagram-frame-uri="${frameUri}" data-local-diagram-script-uri="${resource('media', 'local-diagram-frame.js')}" data-plant-uml-viz-script-uri="${resource('media', 'plantuml-viz-global.js')}">
<script src="${resource('dist', 'test', 'localDiagramProbe.js')}"></script></body></html>`;
      const report = await finished;
      assert.strictEqual(report.sandbox, 'allow-scripts');
      assert.match(String(report.plantumlSvg), /^<svg\b/);
      assert.match(String(report.graphvizSvg), /<svg\b/);
      assert.strictEqual(report.error, '');
      assert.deepStrictEqual(report.cspErrors, []);
    } finally {
      panel.dispose();
    }
  });
});
