import { expect, it, vi } from 'vitest';
import { renderGraphviz } from '../../src/webview/renderers/graphviz.js';

const instance = vi.hoisted(() => vi.fn());
vi.mock('@viz-js/viz', () => ({ instance }));

it('reuses one Viz instance, makes the canvas transparent, and keeps later DOT renders usable after an error', async () => {
  const graphvizSvg = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz -->
<svg xmlns="http://www.w3.org/2000/svg">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 112)">
<title>G</title>
<polygon fill="white" stroke="none" points="-4,4 -4,-112 58,-112 58,4 -4,4"/>
<g id="node1" class="node"><ellipse fill="white" stroke="black" cx="27" cy="-90" rx="27" ry="18"/></g>
</g>
</svg>`;
  const renderString = vi.fn()
    .mockImplementationOnce(() => { throw new Error('syntax error near line 3'); })
    .mockReturnValueOnce('<svg xmlns="http://www.w3.org/2000/svg"></svg>')
    .mockReturnValue(graphvizSvg);
  instance.mockResolvedValue({ renderString });

  await expect(renderGraphviz('digraph { A -> }')).rejects.toThrow('syntax error near line 3');
  await expect(renderGraphviz('digraph { A -> B }')).resolves.toContain('<svg');
  const normalizedSvg = await renderGraphviz('digraph { B -> C }');
  const darkSvg = await renderGraphviz('digraph { C -> D }', true);
  expect(normalizedSvg).toContain('<svg');
  expect(normalizedSvg).not.toMatch(/<\?xml|<!DOCTYPE/i);
  expect(normalizedSvg).not.toContain('<polygon fill="white" stroke="none"');
  expect(normalizedSvg).toContain('<ellipse fill="white" stroke="black"');
  expect(darkSvg).not.toContain('<polygon fill="white" stroke="none"');
  expect(renderString.mock.calls[2][1]).toEqual({ format: 'svg', graphAttributes: { bgcolor: 'transparent' } });
  expect(renderString.mock.calls[3][1]).toEqual({
    format: 'svg',
    graphAttributes: { bgcolor: 'transparent', fontcolor: '#e6edf3' },
    nodeAttributes: { color: '#c9d1d9', fontcolor: '#e6edf3' },
    edgeAttributes: { color: '#c9d1d9', fontcolor: '#e6edf3' }
  });
  expect(instance).toHaveBeenCalledTimes(1);
  expect(renderString).toHaveBeenCalledTimes(4);
});
