import { expect, it, vi } from 'vitest';
import { renderGraphviz } from '../../src/webview/renderers/graphviz.js';

const instance = vi.hoisted(() => vi.fn());
vi.mock('@viz-js/viz', () => ({ instance }));

it('reuses one Viz instance and keeps later DOT renders usable after an error', async () => {
  const graphvizSvg = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz -->
<svg xmlns="http://www.w3.org/2000/svg"></svg>`;
  const renderString = vi.fn()
    .mockImplementationOnce(() => { throw new Error('syntax error near line 3'); })
    .mockReturnValueOnce('<svg xmlns="http://www.w3.org/2000/svg"></svg>')
    .mockReturnValue(graphvizSvg);
  instance.mockResolvedValue({ renderString });

  await expect(renderGraphviz('digraph { A -> }')).rejects.toThrow('syntax error near line 3');
  await expect(renderGraphviz('digraph { A -> B }')).resolves.toContain('<svg');
  const normalizedSvg = await renderGraphviz('digraph { B -> C }');
  expect(normalizedSvg).toContain('<svg');
  expect(normalizedSvg).not.toMatch(/<\?xml|<!DOCTYPE/i);
  expect(instance).toHaveBeenCalledTimes(1);
  expect(renderString).toHaveBeenCalledTimes(3);
});
